# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package Publish

on:
  release:
    types: [created]
  push:
    tags:
      - 'v*'  # 在推送版本标签时触发
permissions:
  id-token: write  # 启用 OIDC 令牌
  contents: read
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
          
      - name: 更新 npm 到最新版本
        run: npm install -g npm@latest
        
      - name: 安装依赖
        run: npm ci
        
      - name: 构建
        run: npm run build
        
      - name: 运行测试（如果存在）
        run: npm run test --if-present
        
      - name: 发布到 npm
        run: npm publish
